[general]
filename = "../doc/img/budowa/pulse_out.png"
trigger_ch_index = 0
data_ch_index = 1
time_limit_sec = 0.001
remove_offset = false
x_label = "Czas (μs)"
y_label = "Napięcie (mV)"

[smoothing]
apply = true
window = 401
poly = 3

[visual]
line_width = 1.0

[[files]]
path = "../meas/pulse_out_nometal.edf"
label = "Bazowa odpowiedź sondy"

[[files]]
path = "../meas/pulse_out_metal.edf"
label = "Odpowiedź sondy z metalem w pobliżu"
