name: Build presentation
on: [push]
jobs:
  build_prez:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: doc
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
          root_file: prez.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v5
        with:
          name: Prezentacja
          path: doc/prez.pdf
